using System.Net;
using System.Text;
using FluentAssertions;
using Moq;
using Moq.Protected;
using Trix;
using Trix.Models;

namespace Trix.Tests;

/// <summary>
/// Tests for SpacesResource including slug functionality.
/// </summary>
public class SpacesResourceTests : IDisposable
{
    private readonly Mock<HttpMessageHandler> _mockHandler;
    private readonly HttpClient _httpClient;
    private readonly TrixClient _client;

    public SpacesResourceTests()
    {
        _mockHandler = new Mock<HttpMessageHandler>();
        _httpClient = new HttpClient(_mockHandler.Object)
        {
            BaseAddress = new Uri("https://api.test.com")
        };

        var options = new TrixClientOptions
        {
            ApiKey = "test_key",
            BaseUrl = "https://api.test.com",
            HttpHandler = _mockHandler.Object
        };

        _client = new TrixClient(options);
    }

    public void Dispose()
    {
        _client.Dispose();
        _httpClient.Dispose();
    }

    private void SetupResponse(HttpStatusCode statusCode, string content)
    {
        _mockHandler.Protected()
            .Setup<Task<HttpResponseMessage>>(
                "SendAsync",
                ItExpr.IsAny<HttpRequestMessage>(),
                ItExpr.IsAny<CancellationToken>())
            .ReturnsAsync(new HttpResponseMessage(statusCode)
            {
                Content = new StringContent(content, Encoding.UTF8, "application/json")
            });
    }

    private void SetupResponseWithRequestCapture(HttpStatusCode statusCode, string content, out HttpRequestMessage? capturedRequest)
    {
        HttpRequestMessage? captured = null;
        _mockHandler.Protected()
            .Setup<Task<HttpResponseMessage>>(
                "SendAsync",
                ItExpr.IsAny<HttpRequestMessage>(),
                ItExpr.IsAny<CancellationToken>())
            .Callback<HttpRequestMessage, CancellationToken>((req, _) => captured = req)
            .ReturnsAsync(new HttpResponseMessage(statusCode)
            {
                Content = new StringContent(content, Encoding.UTF8, "application/json")
            });
        capturedRequest = captured;
    }

    #region Slug Field Tests

    [Fact]
    public async Task Space_Should_Have_Slug()
    {
        // Arrange
        var responseJson = """
        {
            "id": "space_123",
            "name": "Test Space",
            "slug": "test-space",
            "description": "A test space",
            "createdAt": "2025-01-01T00:00:00Z",
            "updatedAt": "2025-01-01T00:00:00Z"
        }
        """;
        SetupResponse(HttpStatusCode.OK, responseJson);

        // Act
        var space = await _client.Spaces.GetAsync("space_123");

        // Assert
        space.Should().NotBeNull();
        space.Id.Should().Be("space_123");
        space.Name.Should().Be("Test Space");
        space.Slug.Should().Be("test-space");
    }

    [Fact]
    public async Task Create_With_Custom_Slug()
    {
        // Arrange
        var responseJson = """
        {
            "id": "space_123",
            "name": "Test Space",
            "slug": "custom-slug",
            "description": "A test space",
            "createdAt": "2025-01-01T00:00:00Z",
            "updatedAt": "2025-01-01T00:00:00Z"
        }
        """;

        string? capturedBody = null;
        _mockHandler.Protected()
            .Setup<Task<HttpResponseMessage>>(
                "SendAsync",
                ItExpr.IsAny<HttpRequestMessage>(),
                ItExpr.IsAny<CancellationToken>())
            .Callback<HttpRequestMessage, CancellationToken>((req, _) =>
            {
                capturedBody = req.Content?.ReadAsStringAsync().GetAwaiter().GetResult();
            })
            .ReturnsAsync(new HttpResponseMessage(HttpStatusCode.OK)
            {
                Content = new StringContent(
                    responseJson, Encoding.UTF8, "application/json")
            });

        // Act
        var space = await _client.Spaces.CreateAsync(new CreateSpaceRequest
        {
            Name = "Test Space",
            Slug = "custom-slug",
            Description = "A test space"
        });

        // Assert
        space.Should().NotBeNull();
        space.Slug.Should().Be("custom-slug");

        // Verify request body contained slug
        capturedBody.Should().NotBeNull();
        capturedBody.Should().Contain("\"slug\":\"custom-slug\"");
    }

    [Fact]
    public async Task Create_Without_Slug_AutoGenerated()
    {
        // Arrange
        var responseJson = """
        {
            "id": "space_123",
            "name": "Test Space",
            "slug": "test-space",
            "createdAt": "2025-01-01T00:00:00Z",
            "updatedAt": "2025-01-01T00:00:00Z"
        }
        """;
        SetupResponse(HttpStatusCode.OK, responseJson);

        // Act
        var space = await _client.Spaces.CreateAsync(new CreateSpaceRequest
        {
            Name = "Test Space"
        });

        // Assert
        space.Should().NotBeNull();
        space.Slug.Should().Be("test-space");  // Auto-generated from name
    }

    #endregion

    #region GetBySlug Tests

    [Fact]
    public async Task Get_By_Slug()
    {
        // Arrange
        var responseJson = """
        {
            "id": "space_123",
            "name": "Test Space",
            "slug": "test-space",
            "description": "A test space",
            "createdAt": "2025-01-01T00:00:00Z",
            "updatedAt": "2025-01-01T00:00:00Z"
        }
        """;

        HttpRequestMessage? capturedRequest = null;
        _mockHandler.Protected()
            .Setup<Task<HttpResponseMessage>>(
                "SendAsync",
                ItExpr.IsAny<HttpRequestMessage>(),
                ItExpr.IsAny<CancellationToken>())
            .Callback<HttpRequestMessage, CancellationToken>((req, _) => capturedRequest = req)
            .ReturnsAsync(new HttpResponseMessage(HttpStatusCode.OK)
            {
                Content = new StringContent(responseJson, Encoding.UTF8, "application/json")
            });

        // Act
        var space = await _client.Spaces.GetBySlugAsync("test-space");

        // Assert
        space.Should().NotBeNull();
        space.Id.Should().Be("space_123");
        space.Slug.Should().Be("test-space");

        // Verify correct endpoint was called
        capturedRequest.Should().NotBeNull();
        capturedRequest!.RequestUri!.PathAndQuery.Should().Contain("/spaces/test-space");
    }

    [Fact]
    public async Task GetBySlug_EncodesSpecialCharacters()
    {
        // Arrange
        var responseJson = """
        {
            "id": "space_123",
            "name": "Test Space",
            "slug": "test space",
            "createdAt": "2025-01-01T00:00:00Z",
            "updatedAt": "2025-01-01T00:00:00Z"
        }
        """;

        HttpRequestMessage? capturedRequest = null;
        _mockHandler.Protected()
            .Setup<Task<HttpResponseMessage>>(
                "SendAsync",
                ItExpr.IsAny<HttpRequestMessage>(),
                ItExpr.IsAny<CancellationToken>())
            .Callback<HttpRequestMessage, CancellationToken>((req, _) => capturedRequest = req)
            .ReturnsAsync(new HttpResponseMessage(HttpStatusCode.OK)
            {
                Content = new StringContent(responseJson, Encoding.UTF8, "application/json")
            });

        // Act
        var space = await _client.Spaces.GetBySlugAsync("test space");

        // Assert
        capturedRequest.Should().NotBeNull();
        capturedRequest!.RequestUri!.PathAndQuery.Should().Contain("test%20space");
    }

    [Fact]
    public async Task GetBySlug_EmptySlug_ThrowsArgumentException()
    {
        // Act & Assert
        var act = () => _client.Spaces.GetBySlugAsync("");
        await act.Should().ThrowAsync<ArgumentException>();
    }

    [Fact]
    public async Task GetBySlug_NullSlug_ThrowsArgumentException()
    {
        // Act & Assert
        var act = () => _client.Spaces.GetBySlugAsync(null!);
        await act.Should().ThrowAsync<ArgumentException>();
    }

    #endregion

    #region Update Slug Tests

    [Fact]
    public async Task Update_Slug()
    {
        // Arrange
        var responseJson = """
        {
            "id": "space_123",
            "name": "Test Space",
            "slug": "updated-slug",
            "createdAt": "2025-01-01T00:00:00Z",
            "updatedAt": "2025-01-01T01:00:00Z"
        }
        """;

        string? capturedBody = null;
        _mockHandler.Protected()
            .Setup<Task<HttpResponseMessage>>(
                "SendAsync",
                ItExpr.IsAny<HttpRequestMessage>(),
                ItExpr.IsAny<CancellationToken>())
            .Callback<HttpRequestMessage, CancellationToken>((req, _) =>
            {
                capturedBody = req.Content?.ReadAsStringAsync().GetAwaiter().GetResult();
            })
            .ReturnsAsync(new HttpResponseMessage(HttpStatusCode.OK)
            {
                Content = new StringContent(
                    responseJson, Encoding.UTF8, "application/json")
            });

        // Act
        var space = await _client.Spaces.UpdateAsync("space_123", new UpdateSpaceRequest
        {
            Slug = "updated-slug"
        });

        // Assert
        space.Should().NotBeNull();
        space.Slug.Should().Be("updated-slug");

        // Verify request body contained slug
        capturedBody.Should().NotBeNull();
        capturedBody.Should().Contain("\"slug\":\"updated-slug\"");
    }

    [Fact]
    public async Task Update_Name_And_Slug()
    {
        // Arrange
        var responseJson = """
        {
            "id": "space_123",
            "name": "Updated Name",
            "slug": "updated-slug",
            "createdAt": "2025-01-01T00:00:00Z",
            "updatedAt": "2025-01-01T01:00:00Z"
        }
        """;

        string? capturedBody = null;
        _mockHandler.Protected()
            .Setup<Task<HttpResponseMessage>>(
                "SendAsync",
                ItExpr.IsAny<HttpRequestMessage>(),
                ItExpr.IsAny<CancellationToken>())
            .Callback<HttpRequestMessage, CancellationToken>((req, _) =>
            {
                capturedBody = req.Content?.ReadAsStringAsync().GetAwaiter().GetResult();
            })
            .ReturnsAsync(new HttpResponseMessage(HttpStatusCode.OK)
            {
                Content = new StringContent(
                    responseJson, Encoding.UTF8, "application/json")
            });

        // Act
        var space = await _client.Spaces.UpdateAsync("space_123", new UpdateSpaceRequest
        {
            Name = "Updated Name",
            Slug = "updated-slug"
        });

        // Assert
        space.Should().NotBeNull();
        space.Name.Should().Be("Updated Name");
        space.Slug.Should().Be("updated-slug");

        // Verify request body
        capturedBody.Should().NotBeNull();
        capturedBody.Should().Contain("\"name\":\"Updated Name\"");
        capturedBody.Should().Contain("\"slug\":\"updated-slug\"");
    }

    #endregion

    #region Basic CRUD Tests

    [Fact]
    public async Task CreateAsync_ValidRequest_ReturnsSpace()
    {
        // Arrange
        var responseJson = """
        {
            "id": "space_new",
            "name": "New Space",
            "slug": "new-space",
            "description": "A new space",
            "createdAt": "2025-01-01T00:00:00Z",
            "updatedAt": "2025-01-01T00:00:00Z"
        }
        """;
        SetupResponse(HttpStatusCode.OK, responseJson);

        // Act
        var space = await _client.Spaces.CreateAsync(new CreateSpaceRequest
        {
            Name = "New Space",
            Description = "A new space"
        });

        // Assert
        space.Should().NotBeNull();
        space.Id.Should().Be("space_new");
        space.Name.Should().Be("New Space");
        space.Slug.Should().Be("new-space");
    }

    [Fact]
    public async Task ListAsync_ReturnsSpaces()
    {
        // Arrange
        var responseJson = """
        {
            "data": [
                {
                    "id": "space_1",
                    "name": "Space 1",
                    "slug": "space-1",
                    "createdAt": "2025-01-01T00:00:00Z",
                    "updatedAt": "2025-01-01T00:00:00Z"
                },
                {
                    "id": "space_2",
                    "name": "Space 2",
                    "slug": "space-2",
                    "createdAt": "2025-01-01T00:00:00Z",
                    "updatedAt": "2025-01-01T00:00:00Z"
                }
            ],
            "pagination": { "total": 2, "page": 1, "limit": 100, "hasMore": false }
        }
        """;
        SetupResponse(HttpStatusCode.OK, responseJson);

        // Act
        var result = await _client.Spaces.ListAsync();

        // Assert
        result.Should().NotBeNull();
        result.Data.Should().HaveCount(2);
        result.Data[0].Slug.Should().Be("space-1");
        result.Data[1].Slug.Should().Be("space-2");
    }

    [Fact]
    public async Task GetAsync_ValidId_ReturnsSpace()
    {
        // Arrange
        var responseJson = """
        {
            "id": "space_123",
            "name": "Test Space",
            "slug": "test-space",
            "createdAt": "2025-01-01T00:00:00Z",
            "updatedAt": "2025-01-01T00:00:00Z"
        }
        """;
        SetupResponse(HttpStatusCode.OK, responseJson);

        // Act
        var space = await _client.Spaces.GetAsync("space_123");

        // Assert
        space.Should().NotBeNull();
        space.Id.Should().Be("space_123");
    }

    [Fact]
    public async Task GetAsync_NullId_ThrowsArgumentException()
    {
        // Act & Assert
        var act = () => _client.Spaces.GetAsync(null!);
        await act.Should().ThrowAsync<ArgumentException>();
    }

    [Fact]
    public async Task GetAsync_EmptyId_ThrowsArgumentException()
    {
        // Act & Assert
        var act = () => _client.Spaces.GetAsync("");
        await act.Should().ThrowAsync<ArgumentException>();
    }

    [Fact]
    public async Task DeleteAsync_ValidId_Succeeds()
    {
        // Arrange
        SetupResponse(HttpStatusCode.NoContent, "");

        // Act & Assert
        var act = () => _client.Spaces.DeleteAsync("space_123");
        await act.Should().NotThrowAsync();
    }

    #endregion
}
